[versions]
# default versions
compileSdk = "35"
minSdk = "29"
targetSdk = "35"
versionCode = "10"
versionName = "1.6.1"
jvmTarget = "17"
# dependencies versions
accompanistPermissions = "0.36.0"
agp = "8.6.1"
datastorePreferences = "1.1.1"
easyvalidationCore = "1.0.4"
firebaseBom = "33.7.0"
firebaseMessagingKtx = "24.1.0"
foundation = "1.7.6"
kotlin = "2.0.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
ksp = "2.0.21-1.0.28"
lottieCompose = "6.4.2-SNAPSHOT"
materialIconsExtended = "1.7.6"
pagingRuntimeKtx = "3.3.5"
pagingCompose = "3.3.5"
playServicesAuth = "21.3.0"
revenuecat = "8.10.1"
roomRuntime = "2.6.1"
roomCompiler = "2.6.1"
composeCharts = "0.0.18"
credentials = "1.3.0"
credentialsPlayServicesAuth = "1.3.0"
googleid = "1.1.1"
# Serialization
runtime = "1.7.6"
serialization = "2.0.21"
serialization-json = "1.7.3"
serialization-core = "1.7.3"
# Hilt
hilt = "2.51.1"
hilt-work = "1.2.0"
hilt-compose = "1.2.0"
# Ktor
ktorClientAndroid = "2.3.5"
ktorClientCore = "3.0.0"
ktorUtils = "3.0.0"
# Coil
coilCompose = "2.7.0"
# Compose Destinations
composeDestinations = "2.1.0-beta09"
composeAnimations = "1.11.6"
# Worker
workRuntime = "2.10.0"
accompanist = "0.34.0"
jakewhartonTimber = "5.0.1"
uiTextGoogleFonts = "1.7.6"
# Retrofit
retrofit = "2.11.0"
loggingInterceptor = "4.12.0"
# PlayServices Ads
playServicesAds = "23.6.0"
googleServices = "4.4.2"
firebaseCrashlytics = "3.0.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
compose-charts = { module = "io.github.ehsannarmani:compose-charts", version.ref = "composeCharts" }
easyvalidation-core = { module = "com.wajahatkarim:easyvalidation-core", version.ref = "easyvalidationCore" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
# Serialization
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization-core" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
# Ktor
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktorUtils" }
# Coil
coil-kt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
# Compose Destinations
compose-destination-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
compose-destination-animation-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "composeAnimations" }
compose-destination-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
# Worker
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
# Timber
jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "jakewhartonTimber" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
# Retrofit
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
#Datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
# PlayServices Ads
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
# Lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
purchases = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecat" }
purchases-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "revenuecat" }

[bundles]
compose = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx", "androidx-activity-compose", "androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling-preview", "androidx-material3", "androidx-material-icons-extended"]
serialization = ["kotlinx-serialization-core", "kotlinx-serialization-json"]
datastore = ["androidx-datastore-preferences", "androidx-datastore-preferences-core"]
ktor = ["ktor-client-android", "ktor-client-core", "ktor-utils"]
retrofit = ["retrofit", "logging-interceptor", "converter-gson"]
android-testing = ["androidx-junit", "androidx-espresso-core", "androidx-ui-test-junit4"]
testing = ["junit"]
debugging = ["androidx-ui-tooling", "androidx-ui-test-manifest"]
roomdb = ["androidx-room-ktx", "androidx-room-runtime"]
revenuecat = ["purchases", "purchases-ui"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }

